on:
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Remote repository (owner/repo)'
        required: true
      base:
        description: 'Base repository (owner/repo) if remote repo has no workflows'
        required: false

name: Import/refresh remote repositories

jobs:
  import_repo:
    runs-on: ubuntu-18.04

    name: Import/refresh ${{ github.ref }} ${{ github.event.inputs.remote_repo }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure Git identity
        run: |
          git log -n 1 --pretty=format:"git config --global user.name '%an' && git config --global user.email '%ae'" | tee /dev/stderr | sh

      - name: Import
        env:
          TOKEN_KEYS: ${{ secrets.TOKEN_KEYS }}
        run: |
          ./run.sh import_base "${{ github.event.inputs.remote_repo }}" "${{ github.event.inputs.base }}" --force
