on:
  create:
  workflow_dispatch:
    inputs:
      remote_repo:
        description: 'Remote repository (owner/repo)'
        required: true

name: Import/refresh remote repositories

jobs:
  import_repo:
    runs-on: ubuntu-18.04

    name: Import/refresh remote repositories

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure Git identity
        run: |
          git log -n 1 --pretty=format:"git config --global user.name '%an' && git config --global user.email '%ae'" | tee /dev/stderr | sh

      - name: Get branch name
        id: remote_repo
        run: |
          echo "::set-output name=slug::$(echo $GITHUB_REF | sed 's#refs/heads/##')"
        shell: bash

      - name: Import
        env:
          TOKEN_KEYS: ${{ secrets.TOKEN_KEYS }}
        run: |
          if [ -n "${{ github.event.inputs.remote_repo }}" ]; then
            remote_repo=${{ github.event.inputs.remote_repo }}
          else
            remote_repo=${{ steps.remote_repo.outputs.slug }}
          fi
          ./run.sh import $remote_repo --force
