on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

name: Refresh all remote repositories

jobs:
  import_repo:
    runs-on: ubuntu-18.04

    name: Refresh all remote repositories

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Configure Git identity
        run: |
          git log -n 1 --pretty=format:"git config --global user.name '%an' && git config --global user.email '%ae'" | tee /dev/stderr | sh

      - name: Import
        env:
          TOKEN_KEYS: ${{ secrets.TOKEN_KEYS }}
        run: |
          ./run.sh refresh_all
