on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/setup-key.yaml'

name: Create deploy key

jobs:
  create_key:
    runs-on: ubuntu-18.04

    name: Create deploy key

    steps:
      - name: ssh-keygen
        run: |
          ssh-keygen -N "" -f id_rsa
        shell: bash

      - name: Delete existing deploy key
        run: |
          curl -s \
            --fail \
            -H"Authorization: token ${{ secrets.TOKEN_KEYS }}" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/keys \
            | tee /dev/stderr \
            | jq '.[] | .id ' | \
            while read _id; do
                    echo "- deploy key: $_id"
                    curl -s \
                      --fail \
                      -X "DELETE" \
                      -H"Authorization: token ${{ secrets.TOKEN_KEYS }}" \
                      https://api.github.com/repos/${GITHUB_REPOSITORY}/keys/$_id
            done
        shell: bash

      - name: Add new deploy key (public)
        run: |
          curl -s \
            --fail \
            -X POST \
            -H"Authorization: token ${{ secrets.TOKEN_KEYS }}" \
            --data @- https://api.github.com/repos/${GITHUB_REPOSITORY}/keys << EOF
            {
              "title" : "Deploy key for linked projects",
              "key" : "$(cat id_rsa.pub)",
              "read_only" : false
            }
          EOF
        shell: bash

      - name: Store private deploy key as secret
        run: |
          curl -s \
            --fail \
            -X POST \
            -H"Authorization: token ${{ secrets.TOKEN_KEYS }}" \
            --data @- https://api.github.com/repos/${GITHUB_REPOSITORY}/secrets << EOF
            {
              "title" : "Deploy key for linked projects",
              "key" : "$(cat id_rsa.pub)",
              "read_only" : false
            }
          EOF
        shell: bash

      - name: Read id_rsa
        id: id_rsa
        uses: juliangruber/read-file-action@v1
        with:
          path: ./id_rsa

      - uses: gliech/create-github-secret-action@v1
        with:
          name: DEPLOY_KEY
          value: ${{ steps.id_rsa.outputs.content }}
          pa_token: ${{ secrets.TOKEN_KEYS }}
