on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/setup-key.yaml'

name: Create deploy key

jobs:
  create_key:
    runs-on: ubuntu-18.04

    name: Generate SSH key

    steps:
      - name: ssh-keygen
        run: |
          ssh-keygen -N "" -f id_rsa
        shell: bash

      - name: Add new deploy key
        run: |
          curl -s \
            --fail \
            -X POST \
            -H"Authorization: token ${{ secrets.TOKEN_KEYS }}" \
            --data @- https://api.github.com/repos/${GITHUB_REPOSITORY}/keys << EOF
            {
              "title" : "Deploy key for linked projects",
              "key" : "$(cat id_rsa.pub)",
              "read_only" : false
            }
            EOF
        shell: bash
